# Generated by Django 2.2.2 on 2019-06-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.TextField()),
                ('cust_Adress', models.TextField(blank=True, max_length=250, null=True)),
                ('cust_password', models.TextField(max_length=100)),
                ('cust_contact', models.TextField(max_length=15)),
                ('cust_email', models.TextField(max_length=100)),
                ('cust_creditno', models.TextField(max_length=20)),
                ('cust_dob', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('itemname', models.TextField(max_length=250)),
                ('itermtype', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookedStatus', models.IntegerField()),
                ('rentCost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopowner',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.TextField()),
                ('owner_Adress', models.TextField(blank=True, max_length=250, null=True)),
                ('owner_password', models.TextField(max_length=100)),
                ('owner_contact', models.TextField(max_length=15)),
                ('owner_email', models.TextField(blank=True, max_length=100, null=True)),
                ('owner_creditno', models.TextField(max_length=20)),
                ('owner_dob', models.TimeField()),
                ('num_shop', models.IntegerField()),
                ('owner_nid', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemamount', models.IntegerField()),
                ('itemprice', models.FloatField()),
                ('itembrand', models.CharField(max_length=20)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Item')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Shopassigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_Date', models.DateField(auto_now=True)),
                ('expire_Date', models.DateField()),
                ('remainPayment', models.FloatField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shopowner')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shop')),
            ],
        ),
    ]
