# Generated by Django 2.2.2 on 2019-06-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190626_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleivaryMan',
            fields=[
                ('delman_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('contact_no', models.TextField()),
                ('availibility', models.BooleanField()),
                ('order_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('order_id', models.TextField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('address', models.TextField()),
                ('is_assigned', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('is_paid', models.BooleanField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Customer')),
                ('delman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.DeleivaryMan')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('order_item_id', models.TextField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Invoice')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('sm_id', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('contact_no', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rev_id', models.TextField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Invoice')),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OrderedItem')),
            ],
        ),
    ]
