# Generated by Django 2.2.2 on 2019-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_deleivaryman_invoice_ordereditem_review_salesmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=30)),
            ],
        ),
    ]
