# Generated by Django 2.2.2 on 2019-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_Adress',
            new_name='cust_Address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_dob',
            field=models.DateField(blank=True),
        ),
    ]
