# Generated by Django 2.2.2 on 2019-07-09 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_shop_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='floor',
            field=models.IntegerField(blank=False,null=False),
            preserve_default=False,
        ),
    ]
