# Generated by Django 2.2.2 on 2019-07-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_shop_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='floor',
        ),
    ]
