# Generated by Django 2.2.2 on 2019-07-10 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190709_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedrent',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
