# Generated by Django 2.2.3 on 2019-07-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_requestedrent_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedrent',
            name='is_granted',
            field=models.BooleanField(default=False),
        ),
    ]
