# Generated by Django 2.2.2 on 2019-07-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190716_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='owner_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
