# Generated by Django 2.2.2 on 2019-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190717_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='owner_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
