# Generated by Django 2.2.2 on 2019-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190717_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='owner_dob',
            field=models.DateField(),
        ),
    ]
