# Generated by Django 2.2.2 on 2019-07-17 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190717_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopassigned',
            name='rent_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
