# Generated by Django 2.2.2 on 2019-07-17 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190717_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopassigned',
            name='expire_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
